######################################################################
# Automatically generated by qmake (3.0) ?? ??? 21 10:30:13 2019
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QT+=widgets
# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
